# -*- coding: utf-8 -*-
"""cleaning_parkir_itn (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HA-4iKOvDmOrW_sRKQQtzNgp5OkMg3Lk

# Data Cleansing Parkir ITN Malang

## 1. Import & Setup
"""

import io
import re
import numpy as np
import pandas as pd

"""## 2. Load Dataset"""

DATA_KOTOR = """ID,Plat_Nomor,Jenis,Merk,Model,Warna,Status,Tanggal,Jam_Masuk,Jam_Keluar,Area
1,N 4521 AB,Motor,Honda,Beat,Merah,Mahasiswa,2026-09-01,07:15,15:30,Kampus 1 - Motor
2,n4521ab,motor,HONDA,beat,merah,mahasiswa,01/09/2026,07:20,15:35,kampus 1 - motor
3,N 1287 CD,Mobil,Toyota,Innova,Silver,Dosen,2026-09-01,08:00,16:00,Kampus 1 - Mobil
4,N 6610 XY,Motor,Yamaha,NMAX,Biru,Mahasiswa,1 Sep 2026,7.45,14.10,Kampus 1 - Motor
5,N 9012 EF,mobil,Honda,Brio,Putih,Dosen,2026-09-02,08:30,08:10,Kampus 1 - Mobil
6,AG 7788 GH,Motor,Suzuki,Satria F150,Biru,Mahasiswa,2026-09-02,09:00,17:00,Kampus 2 - Motor
7,N 3456 IJ,Motor,Honda,Vario 125,Biru,Mahasiswa,2026-09-02,07:50,NULL,Kampus 2 - Motor
8,N-2468-KL,Mobil,Daihatsu,Xenia,Hitam,Staf,2026-09-03,07:30,16:30,kampus 1 - mobil
9,DK 1357 MN,Sepeda Motor,Honda,Supra X 125,Hijau,Tamu,2026-09-03,10:00,11:30,Kampus 2 - Motor
10,N 8642 OP,Motor,Honda,PCX,Oranye,Mahasiswa,2026-09-03,25:10,15:00,Kampus 2 - Motor
11,,Motor,Kawasaki,Ninja 250,Hijau,Mahasiswa,2026-09-04,08:05,12:00,Kampus 1 - Motor
12,N 1111 QR,Mobill,Toyota,Avanza,Abu-abu,Dosn,2026-09-04,08:15,17:45,Kampus 1 - Mobil
13,N 2222 ST,Motor,Honda,Scoopy,Kuning,Mahasiswa ,2026-09-04,07:10,16:20,Kampus 3 - Motor
14,N 3333 UV,Motor,yamaha,Mio,Merah,Mahasiswa,04-09-2026,09:30,13:00,Kampus 1 - Motor
15,B 4444 WX,Mobil,Mitsubishi,Xpander,Coklat,Tamu,2026-09-05,13:00,14:00,Kampus 2 - Mobil
16,N 5555 YZ,Motor,Honda,Vario,Coklat,Mahasiswa,2026-09-05,07:00,07:00,Kampus 1 - Motor
17,N 6666 AA,Motor,Honda,Genio,Maroon,Mahasiswa,2026-09-05,06:45,99:99,Kampus 1 - Motor
18,N 7777 BB,Sepeda,Polygon,Xtrada,Biru,Mahasiswa,2026-09-06,08:00,12:30,Kampus 2 - Motor
19,N 8888 CC,Mobil,Toyota,Fortuner,Putih,Dosen,2026-09-06,08:00,2026-09-07 08:00,Kampus 2 - Mobil
20,N 9999 DD,Motor,Honda,CB150R,Hitam,Staf,2026-09-06,07:30,16:00,Kampus 1 - Motor
21,N 1010 EE,Motor,Yamaha,Aerox,Biru Tua,Mahasiswa,2026-09-07,07:40,15:00,Kampus 2 - Motor
22,N 1010 EE,Motor,Yamaha,Aerox,Biru Tua,Mahasiswa,2026-09-07,07:40,15:00,Kampus 2 - Motor
23,N 1212 FF,Motor,Honda,Beat,Merah,N/A,2026-09-07,08:20,16:10,Kampus 2 - Motor
24,N 1313 GG,Mobil,Suzuki,Ertiga,Silver,Dosen,2027-01-15,09:00,15:00,Kampus 1 - Mobil
25,N 1414 HH,Motor,Honda,Scopy,Krem,Mahasiswa,2026-09-08,7:5,16:00,Kampus 1 - Motor
26,N 1515 II,MOTOR,HONDA,VARIO,BIRU,MAHASISWA,2026-09-08,08:10,17:00,KAMPUS 1 - MOTOR
27,N 1616 JJ,Motor,Honda,,Abu abu,Mahasiswa,2026-09-08,08:30,16:45,Kampus 2 - Motor
28,N1717KK,Mobil,Honda,Jazz,Putih,Staf,2026-09-09,08:00,17:00,Kampus 1 - Mobil
29,N 1818 LL,Motor,Yamaha,Mio,Hijau,Mahasiswa,2026-09-09,07:55,16:05,Kampus 1 - Motor
30,N 1919 MM,Motor,Honda,Beat,Grey,Tamu,9/9/26,12:00,13:15,
"""

df = pd.read_csv(io.StringIO(DATA_KOTOR), dtype=str, keep_default_na=False)
df.head(10)

"""## 3. Data Understanding"""

print("Ukuran data:", df.shape)
df.info()

for kolom in ["Jenis", "Merk", "Model", "Warna", "Status", "Area"]:
    print(f"\n--- {kolom} ---")
    print(df[kolom].value_counts(dropna=False).to_string())

"""## 4. Handling Missing Values"""

df_awal = df.copy()  # simpan salinan untuk perbandingan sebelum/sesudah

for kolom in df.columns:
    df[kolom] = df[kolom].str.strip()

df = df.replace({"": np.nan, "NULL": np.nan, "N/A": np.nan, "-": np.nan})
print(df.isna().sum())

"""## 5. Plate Number Standardization"""

def rapikan_plat(x):
    if pd.isna(x):
        return np.nan
    x = re.sub(r"[^A-Za-z0-9]", "", x).upper()        # buang spasi dan tanda hubung
    m = re.match(r"^([A-Z]{1,2})(\d{1,4})([A-Z]{1,3})$", x)
    return f"{m.group(1)} {m.group(2)} {m.group(3)}" if m else np.nan

df["Plat_Nomor"] = df["Plat_Nomor"].apply(rapikan_plat)

"""## 6. Data Standardization"""

for kolom in ["Jenis", "Merk", "Model", "Warna", "Status", "Area"]:
    df[kolom] = df[kolom].str.title()

df["Jenis"] = df["Jenis"].replace({"Mobill": "Mobil", "Sepeda Motor": "Motor"})
df["Model"] = df["Model"].replace({
    "Scopy": "Scoopy",        # typo
    "Vario 125": "Vario",     # model sama
    "Nmax": "NMAX", "Pcx": "PCX", "Cb150R": "CB150R",   # title() merusak singkatan
})
df["Warna"] = df["Warna"].replace({"Abu Abu": "Abu-abu", "Abu-Abu": "Abu-abu", "Grey": "Abu-abu"})
df["Status"] = df["Status"].replace({"Dosn": "Dosen"})
df["Status"] = df["Status"].fillna("Tidak Diketahui")

for kolom in ["Jenis", "Merk", "Model", "Warna", "Status", "Area"]:
    print(f"\n--- {kolom} ---")
    print(df[kolom].value_counts(dropna=False).to_string())

"""## 7. Date Correction"""

FORMAT_TANGGAL = ["%Y-%m-%d", "%d/%m/%Y", "%d-%m-%Y", "%d %b %Y", "%d/%m/%y"]

def parse_tanggal(x):
    if pd.isna(x):
        return pd.NaT
    for fmt in FORMAT_TANGGAL:
        try:
            return pd.to_datetime(x, format=fmt)
        except ValueError:
            continue
    return pd.NaT

df["Tanggal"] = df["Tanggal"].apply(parse_tanggal)
df["Tanggal"].head(12)

"""## 8. Time Correction"""

df["Menginap"] = df["Jam_Keluar"].str.contains(r"\d{4}-\d{2}-\d{2}", na=False)

def rapikan_jam(x):
    if pd.isna(x):
        return np.nan
    m = re.search(r"(\d{1,2})[:.](\d{1,2})$", x)
    if not m:
        return np.nan
    jam, menit = int(m.group(1)), int(m.group(2))
    if jam > 23 or menit > 59:
        return np.nan
    return f"{jam:02d}:{menit:02d}"

df["Jam_Masuk"] = df["Jam_Masuk"].apply(rapikan_jam)
df["Jam_Keluar"] = df["Jam_Keluar"].apply(rapikan_jam)
df[["ID", "Tanggal", "Jam_Masuk", "Jam_Keluar", "Menginap"]].head(12)

"""## 9. Handling Duplicates"""

sebelum = len(df)
df = df.drop_duplicates(subset=["Plat_Nomor", "Tanggal"], keep="first")
print(f"Baris dihapus: {sebelum - len(df)} (dari {sebelum} menjadi {len(df)})")

"""## 10. Data Validation"""

TANGGAL_BATAS = pd.Timestamp("2026-09-30")
AREA_RESMI = ["Kampus 1 - Motor", "Kampus 1 - Mobil", "Kampus 2 - Motor", "Kampus 2 - Mobil"]

masuk = pd.to_datetime(df["Tanggal"].dt.strftime("%Y-%m-%d") + " " + df["Jam_Masuk"], errors="coerce")
keluar = pd.to_datetime(df["Tanggal"].dt.strftime("%Y-%m-%d") + " " + df["Jam_Keluar"], errors="coerce")
keluar = keluar + pd.to_timedelta(df["Menginap"].astype(int), unit="D")   # menginap: keluar hari berikutnya

df["Durasi_Menit"] = (keluar - masuk).dt.total_seconds() / 60

df["Valid_Durasi"] = df["Durasi_Menit"] > 0
df["Valid_Tanggal"] = df["Tanggal"].notna() & (df["Tanggal"] <= TANGGAL_BATAS)
df["Valid_Area"] = df["Area"].isin(AREA_RESMI)

df[["ID", "Plat_Nomor", "Durasi_Menit", "Valid_Durasi", "Valid_Tanggal", "Valid_Area"]]

"""## 11. Cleaned Dataset"""

df_flag = df.reset_index(drop=True)
df_bersih = df_flag[df_flag["Valid_Durasi"] & df_flag["Valid_Tanggal"] & df_flag["Valid_Area"]].reset_index(drop=True)

print("Data awal      :", len(df_awal), "baris")
print("Setelah dedup  :", len(df_flag), "baris")
print("Data bersih    :", len(df_bersih), "baris")
print("\nBaris bermasalah:")
df_flag[~(df_flag["Valid_Durasi"] & df_flag["Valid_Tanggal"] & df_flag["Valid_Area"])][
    ["ID", "Plat_Nomor", "Tanggal", "Area", "Durasi_Menit", "Valid_Durasi", "Valid_Tanggal", "Valid_Area"]]

df_bersih

"""## 12. Save Cleaned Dataset"""

df_flag.to_csv("data_parkir_flag.csv", index=False)
df_bersih.to_csv("data_parkir_bersih.csv", index=False)

print("File tersimpan: data_parkir_flag.csv dan data_parkir_bersih.csv")